### ISSUE TITLE
lorawan communication goes into busy and needs a reboot to get out 

### ISSUE THREAD

**Issue by digiteyezer** [allthingstalk/att-arduino-lorawan-trackandtrace#4]
The LoraWan modules works for a time (30minutes upto hours). LoRa communication goes into an error state after a while.
See below debug printscreen.

**_Sending payload:
7E 09 00 40 10 00 00 01 17 D9 26 40 57
mac tx cnf 1 7E0900401000000117D9264057
[expectString] expecting ok
.(busy)Failed to send packet
putting the modem into sleep mode
sys sleep 259200000
set wake-up in 1 minutes_**

See also attached screen
![att-trackandtrace](https://cloud.githubusercontent.com/assets/3968264/21451685/2288b772-c901-11e6-8e6c-24888b977e1d.PNG)

Kind regards,
Filip

**Comment by jan-bogaerts** [comment]
Hi Filip,
I suspect that this has something to do with the lora network.  Are you using proximus?  At what frequency are you sending data, ever minute?
Have you tried putting it on a much lower frequency, example every 5 or 10 minutes?
Lora tends to punish devices that send data too often.

Cheers,
Jan.

**Comment by digiteyezer** [comment]
Hi Jan,
Thanks for the very quick reply. I use Proximus Enco.
For testing purposes I used a 1 minute rate which is indeed high. 
The error is immediatelly solved after a hard reboot which did me thinking it was not one LoRa side.
Will check impact of a 5 or 10 minute time slot and keep you informed.

Cheers,
Filip

**Comment by digiteyezer** [comment]
Hi Jan,
Tested with a 5 minute frequency instead of 1 minute. Same result although running for 8 hours before getting the error.
Not sure whether this is linked to LoRa because the problem is solved immediately after a hard reboot (power off/on).

Cheers,
Filip

**Comment by digiteyezer** [comment]
Hi Jan,
Seems the RN2483 goes into a 'busy' status after a time-out waiting for a response is received!
A power off/on solves the issue. Tested with ADR on/off en ACK on/off, adding 5 sec delay between GPS position & speed message with different frequency slots, all resulting into the same problem. It's only a matter of time before the system comes into a 'busy' loop.

See below screenprint.

![att-trackandtrace2](https://cloud.githubusercontent.com/assets/3968264/21478990/4aee89f6-cb51-11e6-8731-b20a8a43bc7b.PNG)

Cheers,
Filip

**Comment by jan-bogaerts** [comment]
Hi Filip,
Have you tried using with intervals of 15 minutes or so? Also, does it recover again after a while, after a day or so? 
The latest we heard from proximus is that there highest plan would be for about 300 messages a day, with the standard package being for about 100, if I remember correctly. I think you are hitting those limits, though this would be a new enforcement on the side of proximus (of which I am not yet aware). I'm currently on holidays and not located in an area that is covered by proximus, so I can't test this myself. But we recently had several devices running for multiple weeks on end, sending data every 15 seconds, on another lora provider, but with the same library (the RDK).

**Comment by digiteyezer** [comment]
Hi Jan,
Setting an interval of 15 minutes (+- 200 messages/day) indeed solves the issue. 
The LoRa Tracl & Trace runs very well now. Disapointing insight on the limits, need to look for another provider...

Thanks for your support.
Happy New Year  

Filip

**Comment by jan-bogaerts** [comment]
Filip,

Thanks for bringing this to our attention. I will pick this up internally with my colleagues. 

Happy new year to you as well.
Jan.
